apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base

# Версії образів - оновлюються через CI/CD
images:
- name: frontend-service
  newName: ghcr.io/yakubovskiyandrey/cloud-fe-sample
  newTag: 4cee0ad2d47c0cf9c809cdb7e5a82d0a133b0ab9
- name: gateway-service
  newName: ghcr.io/yakubovskiyandrey/gateway-service
  newTag: 51e1a5b6257f567fc5fbaffe26b080ac027dbcab
- name: task-service
  newName: ghcr.io/yakubovskiyandrey/task-service
  newTag: de0d59b7c05053c7a1141d7e566d7c3baed7e17a
- name: user-service
  newName: ghcr.io/yakubovskiyandrey/user-service
  newTag: 51e1a5b6257f567fc5fbaffe26b080ac027dbcab
