apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base

# Версії образів - оновлюються через CI/CD
images:
- name: frontend-service
  newName: ghcr.io/yakubovskiyandrey/cloud-fe-sample
  newTag: latest
- name: gateway-service
  newName: ghcr.io/yakubovskiyandrey/gateway-service
  newTag: 27d7678c557d99213b7eecd126c89737e7941dfa
- name: task-service
  newName: ghcr.io/yakubovskiyandrey/task-service
  newTag: 27d7678c557d99213b7eecd126c89737e7941dfa
- name: user-service
  newName: ghcr.io/yakubovskiyandrey/user-service
  newTag: 27d7678c557d99213b7eecd126c89737e7941dfa
