apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base

# Версії образів - оновлюються через CI/CD
images:
- name: frontend-service
  newName: ghcr.io/yakubovskyiandrii/cloud-fe-sample
  newTag: 1d6cbc90aac6fd3d148769ced72c7849421d2ef8
- name: gateway-service
  newName: ghcr.io/yakubovskiyandrey/gateway-service
  newTag: latest
- name: task-service
  newName: ghcr.io/yakubovskiyandrey/task-service
  newTag: latest
- name: user-service
  newName: ghcr.io/yakubovskyiandrii/user-service
  newTag: 27d7678c557d99213b7eecd126c89737e7941dfa
