apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base

# Версії образів - оновлюються через CI/CD
images:
- name: frontend-service
  newName: ghcr.io/yakubovskyiandrii/cloud-fe-sample
  newTag: 4ef1353b9e86e3b0b29439b8aa6ea57c265a4936
- name: gateway-service
  newName: ghcr.io/yakubovskiyandrey/gateway-service
  newTag: latest
- name: task-service
  newName: ghcr.io/yakubovskiyandrey/task-service
  newTag: latest
- name: user-service
  newName: ghcr.io/yakubovskiyandrey/user-service
  newTag: latest
