apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloud-demo

resources:
  # Namespace
  - namespace.yml

  # Infrastructure (databases)
  - postgresql
  - mongodb

  # Services
  - gateway
  - task
  - user
  - frontend

  # Ingress (external access)
  - ingress
